# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 252168d97388b7a5125ade5fdf8c16efcf144fb23878e35dc689d7ff4a316722c644f04e3dd63901bdedcd08bffbcc7611f85f26c5590c9c34d8fe98fb907c22

test:
  secret_key_base: b85c8c51cfecfdd33d320374bdfd844cb5d6cef6b0ea2b92d8dde79b6a8f9725df5561ead6191e5095e82559271518316e683d3d2b37de89050234c42aa1fa4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
